[site]
title = "ChaozNan Warn"
description = "PhD student at Shandong University."
favicon = "/favicon.svg"
last_updated = "December 01, 2025"

[author]
name = "Zhaonan Wang"
title = "PhD Student"
institution = "Shandong University"
avatar = "/mybio.png"

[social]
# Contact information (leave blank or delete to hide)

email = "DyllanElliia_wzn@163.com"
location = "City, Country"
orcid = "https://orcid.org/0009-0002-0124-4819"
github = "https://github.com/DyllanElliia"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
